export const NVIDIA_BUILTIN_TEXT_MODELS = Object["freeze"]([
  Object["freeze"]({
    modelId: "nvidia/meta/llama-3.1-8b-instruct",
    executionId: "nvidia.model-api.text.llama-3-1-8b-instruct.v1",
    displayName: "Llama 3.1 8B Instruct",
    model: "meta/llama-3.1-8b-instruct",
    title: "Llama 3.1 8B",
    subtitle: "Meta 轻量模型，适合高频文本任务",
    icon: "nvidia",
    order: 10,
  }),
  Object["freeze"]({
    modelId: "nvidia/meta/llama-3.3-70b-instruct",
    executionId: "nvidia.model-api.text.llama-3-3-70b-instruct.v1",
    displayName: "Llama 3.3 70B Instruct",
    model: "meta/llama-3.3-70b-instruct",
    title: "Llama 3.3 70B",
    subtitle: "Meta 旗舰开源模型，推理能力强",
    icon: "nvidia",
    order: 20,
  }),
  Object["freeze"]({
    modelId: "nvidia/deepseek-ai/deepseek-r1",
    executionId: "nvidia.model-api.text.deepseek-r1.v1",
    displayName: "DeepSeek R1",
    model: "deepseek-ai/deepseek-r1",
    title: "DeepSeek R1",
    subtitle: "DeepSeek 推理模型",
    icon: "deepseek",
    order: 30,
  }),
  Object["freeze"]({
    modelId: "nvidia/mistralai/mistral-nemo-12b-instruct",
    executionId: "nvidia.model-api.text.mistral-nemo-12b-instruct.v1",
    displayName: "Mistral NeMo 12B",
    model: "mistralai/mistral-nemo-12b-instruct",
    title: "Mistral NeMo 12B",
    subtitle: "Mistral 中等规模指令模型",
    icon: "nvidia",
    order: 40,
  }),
]);
