import test from "node:test";
import strict from "node:assert/strict";
import {
  stripImageGenerationResultStateForDerivedNode,
  stripImageGenerationRuntimeState,
} from "./imageTaskRuntimeState.js";
import { resolveGenerationUiState } from "./generationTaskUiState.js";
(test("imageTaskRuntimeState: 清理图像节点运行态字段但保留业务结果", () => {
  const v0 = {
      id: "node_1",
      provider: "apimart",
      model: "apimart/nano-banana-2",
      isGenerating: true,
      jobStatus: "running",
      taskCancellable: true,
      taskResumable: true,
      taskAdapterType: "workflow",
      generationStartTime: 100,
      generationDuration: 200,
      rhTaskId: "rh-task",
      rhTaskStatus: "running",
      rhTaskStartedAt: 1,
      rhTaskRecovering: true,
      rhTaskUseOpenapiQuery: true,
      rhStatusMessage: "running",
      rhStatusCode: 813,
      dreaminaSubmitId: "dm-submit",
      dreaminaTaskStatus: "pending",
      dreaminaTaskPhase: "generating",
      dreaminaTaskLabel: "生成中",
      dreaminaTaskStartedAt: 2,
      dreaminaTaskLastCheckedAt: 3,
      dreaminaTaskRecovering: true,
      dreaminaTaskLastRaw: { foo: 1 },
      asyncTaskProvider: "apimart",
      asyncTaskKind: "image",
      asyncTaskId: "async-task",
      asyncTaskStatus: "running",
      asyncTaskStartedAt: 4,
      asyncTaskRecovering: true,
      images: [{ imageUrl: "/output/ok.png", localPath: "output/ok.png" }],
      prompt: "cat",
    },
    v1 = stripImageGenerationRuntimeState({ ...v0 });
  (strict["equal"](v1["isGenerating"], undefined),
    strict["equal"](v1["jobStatus"], undefined),
    strict["equal"](v1["taskCancellable"], undefined),
    strict["equal"](v1["taskResumable"], undefined),
    strict["equal"](v1["taskAdapterType"], undefined),
    strict["equal"](v1["generationStartTime"], undefined),
    strict["equal"](v1["generationDuration"], undefined),
    strict["equal"](v1["rhTaskId"], undefined),
    strict["equal"](v1["dreaminaSubmitId"], undefined),
    strict["equal"](v1["asyncTaskId"], undefined),
    strict["deepEqual"](v1["images"], v0["images"]),
    strict["equal"](v1["prompt"], "cat"),
    strict["equal"](resolveGenerationUiState(v1), "idle"));
}),
  test("imageTaskRuntimeState: 复制清理只移除会触发加载的通用运行态", () => {
    const v2 = stripImageGenerationRuntimeState({
      id: "node_done",
      isGenerating: false,
      jobStatus: "success",
      images: [{ imageUrl: "/output/ok.png" }],
    });
    (strict["equal"](v2["isGenerating"], undefined),
      strict["equal"](v2["jobStatus"], "success"),
      strict["deepEqual"](v2["images"], [{ imageUrl: "/output/ok.png" }]));
  }),
  test("imageTaskRuntimeState:\x20派生新生图节点时清理预览上传图片结果但保留配置", () => {
    const v3 = {
        id: "node_1",
        provider: "apimart",
        model: "apimart/nano-banana-2",
        aspectRatio: "自适应",
        imageSize: "4K",
        rhResolution: 1440,
        generationStartTime: 100,
        generationDuration: 200,
        rhTaskId: "rh-task",
        rhTaskStatus: "running",
        rhTaskStartedAt: 1,
        rhTaskRecovering: true,
        rhTaskUseOpenapiQuery: true,
        rhStatusMessage: "running",
        rhStatusCode: 813,
        dreaminaSubmitId: "dm-submit",
        dreaminaTaskStatus: "pending",
        dreaminaTaskPhase: "generating",
        dreaminaTaskLabel: "生成中",
        dreaminaTaskStartedAt: 2,
        dreaminaTaskLastCheckedAt: 3,
        dreaminaTaskRecovering: true,
        dreaminaTaskLastRaw: { foo: 1 },
        asyncTaskProvider: "apimart",
        asyncTaskKind: "image",
        asyncTaskId: "async-task",
        asyncTaskStatus: "running",
        asyncTaskStartedAt: 4,
        asyncTaskRecovering: true,
        images: [
          {
            imageUrl: "/data/uploads/preview-display.webp",
            sourceUrl: "/data/uploads/preview-original.png",
            localPath: "data/uploads/preview-original.png",
            originalLocalPath: "data/uploads/preview-original.png",
            displayLocalPath: "data/uploads/preview-display.webp",
            thumbLocalPath: "data/uploads/preview-thumb.webp",
            fileName: "preview.png",
          },
        ],
        imageUrl: "/data/uploads/preview-display.webp",
        sourceUrl: "/data/uploads/preview-original.png",
        thumbUrl: "/data/uploads/preview-thumb.webp",
        sourceId: "source-id",
        thumbId: "thumb-id",
        src: "/data/uploads/preview-display.webp",
        url: "/data/uploads/preview-display.webp",
        resultUrl: "/data/uploads/preview-display.webp",
        localPath: "data/uploads/preview-original.png",
        originalLocalPath: "data/uploads/preview-original.png",
        displayLocalPath: "data/uploads/preview-display.webp",
        thumbLocalPath: "data/uploads/preview-thumb.webp",
        fileName: "preview.png",
        isImagesExpanded: true,
        mainImageIndex: 0,
        mask: "output/mask/mask.png",
        maskPreview: "output/mask_preview/mask-preview.png",
        maskPreviewUrl: "/output/mask_preview/mask-preview.png",
        maskPolarity: "paint-white",
        maskSaveToken: "mask-save-token",
        status: "success",
        progress: 100,
        error: "old error",
        prompt: "cat",
      },
      v4 = stripImageGenerationResultStateForDerivedNode({ ...v3 });
    (strict["equal"](v4["images"], undefined),
      strict["equal"](v4["imageUrl"], undefined),
      strict["equal"](v4["sourceUrl"], undefined),
      strict["equal"](v4["thumbUrl"], undefined),
      strict["equal"](v4["sourceId"], undefined),
      strict["equal"](v4["thumbId"], undefined),
      strict["equal"](v4["src"], undefined),
      strict["equal"](v4["url"], undefined),
      strict["equal"](v4["resultUrl"], undefined),
      strict["equal"](v4["localPath"], undefined),
      strict["equal"](v4["originalLocalPath"], undefined),
      strict["equal"](v4["displayLocalPath"], undefined),
      strict["equal"](v4["thumbLocalPath"], undefined),
      strict["equal"](v4["fileName"], undefined),
      strict["equal"](v4["isImagesExpanded"], undefined),
      strict["equal"](v4["mainImageIndex"], undefined),
      strict["equal"](v4["mask"], undefined),
      strict["equal"](v4["maskPreview"], undefined),
      strict["equal"](v4["maskPreviewUrl"], undefined),
      strict["equal"](v4["maskPolarity"], undefined),
      strict["equal"](v4["maskSaveToken"], undefined),
      strict["equal"](v4["generationStartTime"], undefined),
      strict["equal"](v4["generationDuration"], undefined),
      strict["equal"](v4["rhTaskId"], undefined),
      strict["equal"](v4["dreaminaSubmitId"], undefined),
      strict["equal"](v4["asyncTaskId"], undefined),
      strict["equal"](v4["status"], undefined),
      strict["equal"](v4["progress"], undefined),
      strict["equal"](v4["error"], undefined),
      strict["equal"](v4["provider"], "apimart"),
      strict["equal"](v4["model"], "apimart/nano-banana-2"),
      strict["equal"](v4["aspectRatio"], "自适应"),
      strict["equal"](v4["imageSize"], "4K"),
      strict["equal"](v4["rhResolution"], 1440),
      strict["equal"](v4["prompt"], "cat"));
  }));
