const DREAMINA_VIDEO_EXECUTION_ID = "dreamina.local-runtime.video.seedance.v1";
export const DREAMINA_VIDEO_VIP_GATE_ID = "dreamina/video_vip";
const VIDEO_ROUTE_MODE_FIELD = Object["freeze"]({
    id: "dreaminaRouteMode",
    type: "segmented",
    placement: "mode",
    label: "Mode",
    defaultValue: "multimodal2video",
    options: Object["freeze"]([
      Object["freeze"]({ value: "multimodal2video", label: "全能参考" }),
      Object["freeze"]({ value: "frames2video", label: "首尾帧" }),
    ]),
  }),
  VIDEO_RESOLUTION_FIELD = Object["freeze"]({
    id: "resolution",
    type: "segmented",
    placement: "resolution",
    label: "Resolution",
    defaultValue: "720p",
    options: Object["freeze"]([
      Object["freeze"]({ value: "720p", label: "720p" }),
      Object["freeze"]({ value: "1080p", label: "1080p" }),
    ]),
  }),
  VIDEO_RATIO_FIELD = Object["freeze"]({
    id: "aspectRatio",
    type: "segmented",
    placement: "resolution",
    label: "Ratio",
    defaultValue: "自适应",
    options: Object["freeze"]([
      Object["freeze"]({ value: "自适应", label: "自适应" }),
      Object["freeze"]({ value: "1:1", label: "1:1" }),
      Object["freeze"]({ value: "3:4", label: "3:4" }),
      Object["freeze"]({ value: "16:9", label: "16:9" }),
      Object["freeze"]({ value: "4:3", label: "4:3" }),
      Object["freeze"]({ value: "9:16", label: "9:16" }),
      Object["freeze"]({ value: "21:9", label: "21:9" }),
    ]),
  }),
  VIDEO_DURATION_FIELD = Object["freeze"]({
    id: "duration",
    type: "slider",
    placement: "duration",
    label: "Duration",
    defaultValue: 5,
    min: 4,
    max: 15,
    step: 1,
  }),
  DREAMINA_VIDEO_UI_SCHEMA = Object["freeze"]({
    fields: Object["freeze"]([
      VIDEO_ROUTE_MODE_FIELD,
      VIDEO_RESOLUTION_FIELD,
      VIDEO_RATIO_FIELD,
      VIDEO_DURATION_FIELD,
    ]),
  }),
  DREAMINA_VIDEO_INPUT_SLOTS = Object["freeze"]({
    allowedKinds: Object["freeze"](["text", "image", "video", "audio"]),
    minByKind: Object["freeze"]({ text: 0 }),
    maxByKind: Object["freeze"]({ image: 9, video: 3, audio: 3 }),
  }),
  DREAMINA_SEEDANCE_TASK_TYPES = Object["freeze"]([
    "text2video",
    "image2video",
    "frames2video",
    "multimodal2video",
  ]),
  DREAMINA_IMAGE_ROUTE_TASK_TYPES = Object["freeze"](["image2video"]),
  DREAMINA_IMAGE_AND_FRAMES_TASK_TYPES = Object["freeze"]([
    "image2video",
    "frames2video",
  ]),
  DREAMINA_SEEDANCE_RESOLUTION_BY_TASK = Object["freeze"]({
    text2video: Object["freeze"](["720p"]),
    image2video: Object["freeze"](["720p"]),
    frames2video: Object["freeze"](["720p"]),
    multimodal2video: Object["freeze"](["720p"]),
  }),
  DREAMINA_SEEDANCE_VIP_RESOLUTION_BY_TASK = Object["freeze"]({
    text2video: Object["freeze"](["720p", "1080p"]),
    image2video: Object["freeze"](["720p", "1080p"]),
    frames2video: Object["freeze"](["720p", "1080p"]),
    multimodal2video: Object["freeze"](["720p", "1080p"]),
  }),
  DREAMINA_720_1080_RESOLUTION_BY_TASK = Object["freeze"]({
    image2video: Object["freeze"](["720p", "1080p"]),
    frames2video: Object["freeze"](["720p", "1080p"]),
  }),
  DREAMINA_1080_RESOLUTION_BY_TASK = Object["freeze"]({
    image2video: Object["freeze"](["1080p"]),
  }),
  DREAMINA_DEFAULT_DURATION_BY_TASK = Object["freeze"]({
    text2video: Object["freeze"]({ min: 4, max: 15, step: 1 }),
    image2video: Object["freeze"]({ min: 4, max: 15, step: 1 }),
    frames2video: Object["freeze"]({ min: 4, max: 15, step: 1 }),
    multimodal2video: Object["freeze"]({ min: 4, max: 15, step: 1 }),
  }),
  DREAMINA_SHORT_DURATION_BY_TASK = Object["freeze"]({
    image2video: Object["freeze"]({ min: 3, max: 10, step: 1 }),
    frames2video: Object["freeze"]({ min: 3, max: 10, step: 1 }),
  }),
  DREAMINA_35_PRO_DURATION_BY_TASK = Object["freeze"]({
    image2video: Object["freeze"]({ min: 4, max: 12, step: 1 }),
    frames2video: Object["freeze"]({ min: 4, max: 12, step: 1 }),
  }),
  DREAMINA_VIDEO_MODEL_MENU_ENTRIES = Object["freeze"]([
    Object["freeze"]({
      modelId: "dreamina/seedance2.0fast_vip",
      displayName: "Seedance 2.0 Fast VIP",
      counterpartKey: "seedance2-fast",
      order: 10,
      title: "Seedance\x202.0\x20Fast\x20VIP",
      subtitle: "高速高阶版，支持全能参考与首尾帧链路",
      taskTypes: DREAMINA_SEEDANCE_TASK_TYPES,
      resolutionOptionsByTaskType: DREAMINA_SEEDANCE_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_DEFAULT_DURATION_BY_TASK,
      vip: true,
    }),
    Object["freeze"]({
      modelId: "dreamina/seedance2.0_vip",
      displayName: "Seedance 2.0 VIP",
      counterpartKey: "seedance2-standard",
      order: 20,
      title: "Seedance 2.0 VIP",
      subtitle: "质量优先，支持 1080p 全能参考与首尾帧链路",
      taskTypes: DREAMINA_SEEDANCE_TASK_TYPES,
      resolutionOptionsByTaskType: DREAMINA_SEEDANCE_VIP_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_DEFAULT_DURATION_BY_TASK,
      vip: true,
    }),
    Object["freeze"]({
      modelId: "dreamina/seedance2.0fast",
      displayName: "Seedance\x202.0\x20Fast",
      counterpartKey: "seedance2-fast",
      order: 30,
      title: "Seedance 2.0 Fast",
      subtitle: "默认推荐，支持文生、图生、首尾帧、全能参考",
      taskTypes: DREAMINA_SEEDANCE_TASK_TYPES,
      aliases: Object["freeze"](["seedance-2.0-fast"]),
      defaultForTaskTypes: DREAMINA_SEEDANCE_TASK_TYPES,
      resolutionOptionsByTaskType: DREAMINA_SEEDANCE_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_DEFAULT_DURATION_BY_TASK,
    }),
    Object["freeze"]({
      modelId: "dreamina/seedance2.0",
      displayName: "Seedance 2.0",
      counterpartKey: "seedance2-standard",
      order: 40,
      title: "Seedance 2.0",
      subtitle: "质量更稳，支持文生、图生、首尾帧、全能参考",
      taskTypes: DREAMINA_SEEDANCE_TASK_TYPES,
      aliases: Object["freeze"](["seedance-2.0"]),
      resolutionOptionsByTaskType: DREAMINA_SEEDANCE_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_DEFAULT_DURATION_BY_TASK,
    }),
    Object["freeze"]({
      modelId: "dreamina/3.5pro",
      displayName: "即梦 3.5 Pro",
      order: 50,
      title: "即梦\x203.5\x20Pro",
      subtitle: "细节更稳，支持首帧与首尾帧",
      subtitleByTaskType: Object["freeze"]({ frames2video: "首尾帧细节更稳" }),
      taskTypes: DREAMINA_IMAGE_AND_FRAMES_TASK_TYPES,
      aliases: Object["freeze"](["dreamina/3.5_pro"]),
      resolutionOptionsByTaskType: DREAMINA_720_1080_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_35_PRO_DURATION_BY_TASK,
    }),
    Object["freeze"]({
      modelId: "dreamina/3.0pro",
      displayName: "即梦\x203.0\x20Pro",
      order: 60,
      title: "即梦 3.0 Pro",
      subtitle: "1080p 图生视频，适合首帧单图驱动",
      taskTypes: DREAMINA_IMAGE_ROUTE_TASK_TYPES,
      aliases: Object["freeze"](["dreamina/3.0_pro"]),
      resolutionOptionsByTaskType: DREAMINA_1080_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_SHORT_DURATION_BY_TASK,
    }),
    Object["freeze"]({
      modelId: "dreamina/3.0fast",
      displayName: "即梦 3.0 Fast",
      order: 70,
      title: "即梦 3.0 Fast",
      subtitle: "更快的单图视频生成",
      taskTypes: DREAMINA_IMAGE_ROUTE_TASK_TYPES,
      aliases: Object["freeze"](["dreamina/3.0_fast"]),
      resolutionOptionsByTaskType: Object["freeze"]({
        image2video: Object["freeze"](["720p", "1080p"]),
      }),
      durationRangeByTaskType: DREAMINA_SHORT_DURATION_BY_TASK,
    }),
    Object["freeze"]({
      modelId: "dreamina/3.0",
      displayName: "即梦 3.0",
      order: 80,
      title: "即梦 3.0",
      subtitle: "支持首帧与首尾帧的基础模型",
      subtitleByTaskType: Object["freeze"]({
        frames2video: "支持首尾帧与 1080p",
      }),
      taskTypes: DREAMINA_IMAGE_AND_FRAMES_TASK_TYPES,
      resolutionOptionsByTaskType: DREAMINA_720_1080_RESOLUTION_BY_TASK,
      durationRangeByTaskType: DREAMINA_SHORT_DURATION_BY_TASK,
    }),
  ]);
function createDreaminaVideoModelManifest(v0) {
  return Object["freeze"]({
    schemaVersion: "1.0",
    modelId: v0["modelId"],
    ...(Array["isArray"](v0["aliases"]) ? { aliases: v0["aliases"] } : {}),
    provider: "dreamina",
    kind: "video",
    adapterType: "localRuntime",
    executionId: DREAMINA_VIDEO_EXECUTION_ID,
    displayName: v0["displayName"],
    icon: "images/jimeng.png",
    inputSlots: DREAMINA_VIDEO_INPUT_SLOTS,
    uiSchema: DREAMINA_VIDEO_UI_SCHEMA,
    vip: v0["vip"] === true,
    async: true,
    cancellable: true,
    outputType: "video",
    extensions: Object["freeze"]({
      ratioPolicy: Object["freeze"]({ capability: "aspectRatio" }),
      dreaminaStyleVideo: Object["freeze"]({
        order: v0["order"],
        title: v0["title"],
        subtitle: v0["subtitle"],
        subtitleByTaskType: v0["subtitleByTaskType"] || Object["freeze"]({}),
        counterpartKey: v0["counterpartKey"] || "",
        taskTypes: v0["taskTypes"],
        defaultForTaskTypes: v0["defaultForTaskTypes"] || Object["freeze"]([]),
        resolutionOptionsByTaskType:
          v0["resolutionOptionsByTaskType"] || Object["freeze"]({}),
        durationRangeByTaskType:
          v0["durationRangeByTaskType"] || Object["freeze"]({}),
      }),
    }),
  });
}
export const dreaminaOfficialVideoModelManifest = Object["freeze"]({
  schemaVersion: "1.0",
  modelId: "dreamina/text2video",
  provider: "dreamina",
  kind: "video",
  adapterType: "localRuntime",
  executionId: DREAMINA_VIDEO_EXECUTION_ID,
  displayName: "即梦官方",
  icon: "images/jimeng.png",
  inputSlots: DREAMINA_VIDEO_INPUT_SLOTS,
  uiSchema: DREAMINA_VIDEO_UI_SCHEMA,
  vip: true,
  async: true,
  cancellable: true,
  outputType: "video",
  extensions: Object["freeze"]({
    ratioPolicy: Object["freeze"]({ capability: "aspectRatio" }),
    videoMenu: Object["freeze"]({
      role: "dreaminaOfficial",
      order: 10,
      label: "即梦官方",
      subtitle: "无图文生视频，单图图生视频",
      iconAlt: "dreamina",
    }),
  }),
});
export const dreaminaVideoModelManifests = Object["freeze"]([
  dreaminaOfficialVideoModelManifest,
  ...DREAMINA_VIDEO_MODEL_MENU_ENTRIES["map"](createDreaminaVideoModelManifest),
]);
export const dreaminaVideoExecutionManifest = Object["freeze"]({
  schemaVersion: "1.0",
  id: DREAMINA_VIDEO_EXECUTION_ID,
  provider: "dreamina",
  kind: "video",
  adapterType: "localRuntime",
  runtime: "dreaminaVideo",
  result: Object["freeze"]({
    urlFields: Object["freeze"](["url", "videoUrl"]),
  }),
});
export const dreaminaVideoExecutionManifests = Object["freeze"]([
  dreaminaVideoExecutionManifest,
]);
